### ISSUE TITLE
Route not found /api/articles

### ISSUE THREAD

**Issue by cirosantilli** [Utwo/adonis-realworld-example-app#5]
I tried running and visiting http://localhost:3000/api/articles but I get that 404, any clues?

I just copied the `.env` without changing anything. Is there anything that needs to be changed?

Sorry no time to debug, going through several frameworks at once looking for the best, the usual :-)

ea825b755227abd866ebb5aabe9073dc5b85c8a4

**Comment by Utwo** [comment]
Is just `/articles` without the `/api` part

**Comment by cirosantilli** [comment]
Thanks. I tried that now and saw:

```
{"error":{"message":"select count(`id`) as `__lucid_aggregate` from (select *, (select count(*) from `users` inner join `favorites` on `users`.`id` = `favorites`.`user_id` where `articles`.`id` = `favorites`.`article_id`) as `favorites_count` from `articles`) as `__lucid` - SQLITE_ERROR: no such table: articles","name":"Error","status":500,"frames":[]}}
```

**Comment by Utwo** [comment]
Did you run the migration first?
`node ace migration:run`

**Comment by cirosantilli** [comment]
Ooops, I had deleted the database while in try anything mode and didn't rerun migration, thanks!
