### ISSUE TITLE
SQLITE_ERROR: table articles has no column named author"

### ISSUE THREAD

**Issue by ppastene** [Utwo/adonis-realworld-example-app#6]
I'm running the server on dev using the default SQLite database, also I'm using [Ember Realword](https://github.com/gothinkster/ember-realworld) as the frontend. The registration, login, and account edit works like a charm but when I publish a new article the server returns a 500 code with the following message

`{ message: "insert into `articles` (`author`, `body`, `createdAt`, `description`, `slug`, `title`, `updatedAt`, `user_id`) values (NULL, 'This is trhe content', '2021-05-16 01:39:07.272', 'This is the subtitle', 'this-is-the-title', 'This is the title', '2021-05-16 01:39:07.272', 1) - SQLITE_ERROR: table articles has no column named author", name: "Error", status: 500, … }`

The only configuration done was enabling CORS because I was trying to dockerize the server but this including the frontend are running into the same machine on Windows 10

**Comment by ppastene** [comment]
Sorry for that, I've discover that the problem is from Ember because I've tested another frontend app which is [Vue Realworld](https://github.com/khaledosman/vue-realworld-example-app) and it has problems with the JWT token.

My apologies

**Comment by Utwo** [comment]
No problem! Thank you for trying this project :)
